# Generated by Django 3.2.5 on 2021-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_ready_to_distribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ready_to_distribute',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10),
        ),
    ]
